server:
  port: 8000
  servlet:
    context-path: /oauth2-user
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: eureka-client-oauth2-user
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/oauth2?charset=utf-8
    hikari:
      username: postgres
      password: 123456
      minimum-idle: 2
      maximum-pool-size: 8
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

security:
  oauth2:
    resource:
      prefer-token-info: false
      user-info-uri: http://eureka-client-oauth2-user/oauth2-user/

ribbon:
  eager-load:
    enabled: true
