server:
  port: 7000
  servlet:
    context-path: /oauth2-authenticate-server
spring:
  application:
    name: eureka-client-oauth2-authenticate-server
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/oauth2?charset=utf-8
    hikari:
      username: postgres
      password: 123456
      minimum-idle: 2
      max-lifetime: 8
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5000/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  eager-load:
    enabled: true
